services:
  pgdatabase:
    container_name: postgres_container
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
    